name: create-daily-log
on:
  schedule:
    - cron: "30 23 * * 0-4"   # KST 08:30 (Mon–Fri)
  workflow_dispatch:

jobs:
  create:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

      - name: Create Daily Log issue (use template file)
        env:
          GITEA_BASE: http://dev.wyhil.com:43000
          REPO: SG-OHA-2025-TEAM-04/GAON
          TOKEN: ${{ secrets.DAILY_LOG_TOKEN }}
        run: |
          set -e
          TODAY_KST=$(TZ=Asia/Seoul date +%m.%d)
          TITLE="${TODAY_KST} Daily Log"

          # 1) 중복 생성 방지
          Q=$(python3 - <<PY
import urllib.parse as u; print(u.quote("${TITLE}"))
PY
)
          EXIST=$(curl -s -H "Authorization: token $TOKEN" \
            "$GITEA_BASE/api/v1/repos/$REPO/issues/search?q=${Q}&limit=1" \
            | jq -r '.total_count // .issues|length // 0')
          if [ "$EXIST" != "0" ]; then
            echo "Already exists: $TITLE"
            exit 0
          fi

          # 2) 템플릿 파일 원본(raw) 가져오기
          #   (branch는 기본 브랜치 이름으로 교체; develop을 기본으로 썼다면 develop)
          RAW_URL="$GITEA_BASE/api/v1/repos/$REPO/raw/.gitea/ISSUE_TEMPLATE/daily-log.md?ref=develop"
          TEMPLATE=$(curl -fsSL "$RAW_URL")

          # 3) {{date}} 치환
          BODY="${TEMPLATE//\{\{date\}\}/$TODAY_KST}"

          # 4) JSON 페이로드 생성
          PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg body "$BODY" \
            --argjson labels '["type:daily-log"]' \
            --argjson assignees '["edgar_kim","ahnseoyeon","sojy001","zorba"]' \
            '{title:$title, body:$body, labels:$labels, assignees:$assignees}')

          # 5) 이슈 생성
          curl -s -X POST "$GITEA_BASE/api/v1/repos/$REPO/issues" \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            | jq -r '.number // "created"'