name: create-daily-log

on:
  schedule:
    # KST 11:40 (Mon-Fri) == UTC 02:40 (Mon-Fri)
    # - cron: "40 2 * * 1-5"
    - cron: "1 15 4 11 *"
  workflow_dispatch:

jobs:
  create:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

      - name: Create Daily Log issue from template
        env:
          GITEA_BASE: http://dev.wyhil.com:43000
          REPO: SG-OHA-2025-TEAM-04/GAON
          TOKEN: ${{ secrets.DAILY_LOG_TOKEN }}
        run: |
          set -euo pipefail

          TODAY_KST=$(TZ=Asia/Seoul date +%m.%d)
          TITLE="${TODAY_KST} Daily Log"

          echo "::group::Check duplicate issue"
          # Gitea는 /issues/search가 아니라 /issues?q= 로 검색합니다.
          SEARCH_URL="$GITEA_BASE/api/v1/repos/$REPO/issues?q=$(python3 -c "import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1]))" "$TITLE")&state=open&limit=1"
          RESP=$(curl -fsS -H "Authorization: token $TOKEN" "$SEARCH_URL" || true)
          # 응답이 배열이므로 길이로 판정
          COUNT=$(echo "${RESP:-[]}" | jq 'length')
          echo "Found count: $COUNT"
          if [ "${COUNT}" != "0" ]; then
            echo "Already exists: $TITLE"
            exit 0
          fi
          echo "::endgroup::"

          echo "::group::Fetch template"
          # 리포의 raw 파일은 /raw/{filepath}?ref=브랜치 로 접근
          RAW_URL="$GITEA_BASE/api/v1/repos/$REPO/raw/.gitea/ISSUE_TEMPLATE/daily-log.md?ref=develop"
          TEMPLATE=$(curl -fsS -H "Authorization: token $TOKEN" "$RAW_URL")
          BODY_NOFM=$(printf "%s" "$TEMPLATE" | awk '
            BEGIN{fm=0}
            NR==1 && $0=="---"{fm=1; next}
            fm==1 && $0=="---"{fm=2; next}
            fm==0 || fm==2 {print}
          ')
          echo "::endgroup::"

          echo "::group::Build body"
          BODY="${BODY_NOFM//\{\{date\}\}/$TODAY_KST}"
          echo "::endgroup::"

          echo "::group::Create issue"
          PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg body "$BODY" \
            --argjson labels '["type:daily-log"]' \
            --argjson assignees '["edgar_kim","ahnseoyeon","sojy001","zorba","sujung"]' \
            '{title:$title, body:$body, labels:$labels, assignees:$assignees}')

          CREATE_URL="$GITEA_BASE/api/v1/repos/$REPO/issues"
          RESULT=$(curl -fsS -X POST "$CREATE_URL" \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          echo "Created issue #$(echo "$RESULT" | jq -r '.number // "unknown")"
          echo "::endgroup::"