import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import AppNavigation from "@/components/navigation/AppNavigation";
import GlobalHeader from "@/components/navigation/GlobalHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex min-h-[100svh] flex-col">
            <GlobalHeader />

            {/* 콘텐츠 영역: 가로 레이아웃, 남은 높이만 사용 */}
            <div className="mx-auto flex w-full max-w-screen-2xl flex-1 min-h-0 overflow-hidden">
              <AppNavigation />
              <main className="flex-1 min-h-0 overflow-y-auto overflow-x-hidden p-4 pt-1 md:p-6 md:pt-1">
                {/* 전역 Provider로 모든 페이지 감싸기 */}
                {children}
              </main>
            </div>

            {/* 모바일 바텀 네비게이션 자리 확보 */}
            <div className="h-14 md:hidden shrink-0" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
