import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import AppNavigation from "@/components/navigation/AppNavigation";
import GlobalHeader from "@/components/navigation/GlobalHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`min-h-dvh ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <GlobalHeader />
          <div className="mx-auto flex max-w-screen-2xl">
            <AppNavigation />
            <main className="min-h-dvh flex-1 p-4 pt-1 md:p-6 md:pt-1">
              {/* 전역 Provider로 모든 페이지 감싸기 */}
              {children}
            </main>
          </div>
          <div className="h-14 md:hidden"/>
        </Providers>
      </body>
    </html>
  );
}
