name: 💡 기능 요청
description: 새로운 기능을 제안하거나 개선 아이디어를 제시할 때 사용하세요.
title: "[기능] 제안 제목을 간결하게 작성해주세요"
labels: ["enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: 📝 제목
      description: 추가하거나 개선하고 싶은 기능의 제목을 적어주세요.
      placeholder: "예: 다크 모드 지원 추가"

  - type: textarea
    id: problem
    attributes:
      label: 🚩 관련 문제
      description: 이 제안이 어떤 문제를 해결하기 위한 것인지 적어주세요.
      placeholder: "현재 기능에서 어떤 불편함이 있는지 설명해주세요."

  - type: textarea
    id: proposal
    attributes:
      label: 💡 제안 내용
      description: 어떤 해결책이나 기능을 추가하길 원하는지 구체적으로 작성해주세요.
      placeholder: "예: 설정 메뉴에 테마 전환 옵션 추가"

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 대안
      description: 혹시 고려한 다른 해결책이 있다면 적어주세요.
      placeholder: "예: 브라우저 확장 프로그램으로 임시 해결 중"

  - type: input
    id: related
    attributes:
      label: 🗂 관련 항목
      description: 관련된 이슈나 PR이 있다면 적어주세요.
      placeholder: "#10, #25"
