"""add conversation_file table

Revision ID: 604bd5197f7e
Revises: 4cb33c98f6f4
Create Date: 2025-11-06 11:32:30.693277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '604bd5197f7e'
down_revision = '4cb33c98f6f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ideal_answer_created_at', table_name='ideal_answer')
    op.drop_index('idx_ideal_answer_embedding', table_name='ideal_answer', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_ideal_answer_source', table_name='ideal_answer', postgresql_using='gin')
    op.drop_table('ideal_answer')
    op.drop_index('idx_conversation_file_conversation_id', table_name='conversation_file')
    op.drop_index('idx_conversation_file_processing_status', table_name='conversation_file')
    op.drop_index('idx_conversation_file_upload_date', table_name='conversation_file')
    op.drop_table('conversation_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gcs_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunked_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='conversation_file_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversation_file_pkey')
    )
    op.create_index('idx_conversation_file_upload_date', 'conversation_file', ['upload_date'], unique=False)
    op.create_index('idx_conversation_file_processing_status', 'conversation_file', ['processing_status'], unique=False)
    op.create_index('idx_conversation_file_conversation_id', 'conversation_file', ['conversation_id'], unique=False)
    op.create_table('ideal_answer',
    sa.Column('idea_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('analysisid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idea_id', name='ideal_answer_pkey')
    )
    op.create_index('idx_ideal_answer_source', 'ideal_answer', [sa.text("to_tsvector('english'::regconfig, source)")], unique=False, postgresql_using='gin')
    op.create_index('idx_ideal_answer_embedding', 'ideal_answer', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_ideal_answer_created_at', 'ideal_answer', ['created_at'], unique=False)
    # ### end Alembic commands ###