"""add audio fields to conversation_file

Revision ID: 2025_11_11_audio_fields
Revises: be99d0c2f06d
Create Date: 2025-11-11 09:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2025_11_11_audio_fields'
down_revision = 'be99d0c2f06d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_file', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('conversation_file', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('conversation_file', sa.Column('speaker_segments', sa.JSON(), nullable=True))
    op.add_column('conversation_file', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('conversation_file', sa.Column('speaker_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_file', 'speaker_count')
    op.drop_column('conversation_file', 'duration')
    op.drop_column('conversation_file', 'speaker_segments')
    op.drop_column('conversation_file', 'transcript')
    op.drop_column('conversation_file', 'audio_url')
    # ### end Alembic commands ###
