"""Add display_name to realtime_session

Revision ID: d9ea8b908ff6
Revises: 23a1cbb6a510
Create Date: 2025-11-08 11:49:51.950132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9ea8b908ff6'
down_revision = '23a1cbb6a510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ideal_answer_created_at', table_name='ideal_answer')
    op.drop_index('idx_ideal_answer_embedding', table_name='ideal_answer', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_ideal_answer_source', table_name='ideal_answer', postgresql_using='gin')
    op.drop_table('ideal_answer')
    op.drop_table('realtime_message')
    op.drop_table('realtime_session')
    op.drop_index('idx_conversation_file_conversation_id', table_name='conversation_file')
    op.drop_index('idx_conversation_file_processing_status', table_name='conversation_file')
    op.drop_index('idx_conversation_file_upload_date', table_name='conversation_file')
    op.drop_table('conversation_file')
    op.drop_constraint('users_family_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_family_id_fkey', 'users', 'family', ['family_id'], ['id'])
    op.create_table('conversation_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gcs_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunked_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='conversation_file_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversation_file_pkey')
    )
    op.create_index('idx_conversation_file_upload_date', 'conversation_file', ['upload_date'], unique=False)
    op.create_index('idx_conversation_file_processing_status', 'conversation_file', ['processing_status'], unique=False)
    op.create_index('idx_conversation_file_conversation_id', 'conversation_file', ['conversation_id'], unique=False)
    op.create_table('realtime_session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('realtime_session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'ENDED', name='sessionstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='realtime_session_family_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='realtime_session_pkey'),
    sa.UniqueConstraint('room_id', name='realtime_session_room_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('realtime_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'SYSTEM', name='messagetype'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['realtime_session.id'], name='realtime_message_session_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='realtime_message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='realtime_message_pkey')
    )
    op.create_table('ideal_answer',
    sa.Column('idea_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('analysisid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idea_id', name='ideal_answer_pkey')
    )
    op.create_index('idx_ideal_answer_source', 'ideal_answer', [sa.text("to_tsvector('english'::regconfig, source)")], unique=False, postgresql_using='gin')
    op.create_index('idx_ideal_answer_embedding', 'ideal_answer', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_ideal_answer_created_at', 'ideal_answer', ['created_at'], unique=False)
    # ### end Alembic commands ###