"""실시간 대화 테이블 추가

Revision ID: 23a1cbb6a510
Revises: be99d0c2f06d
Create Date: 2025-11-08 10:50:05.043740

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '23a1cbb6a510'
down_revision = 'be99d0c2f06d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 실시간 세션 테이블 생성
    op.create_table('realtime_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='sessionstatus'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    
    # 실시간 메시지 테이블 생성
    op.create_table('realtime_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'SYSTEM', name='messagetype'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['realtime_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realtime_message')
    op.drop_table('realtime_session')
    op.execute("DROP TYPE IF EXISTS sessionstatus")
    op.execute("DROP TYPE IF EXISTS messagetype")
    # ### end Alembic commands ###