"""add_family_and_family_members_tables

Revision ID: 84a14c869175
Revises: 7a1414872d79
Create Date: 2025-11-19 09:12:31.003544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84a14c869175'
down_revision = '7a1414872d79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Family 관련 테이블만 추가
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='_family_user_uc')
    )
    op.create_table('speaker_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'speaker_id', name='_conv_speaker_uc')
    )
    
    # Family 테이블 컬럼 추가
    op.add_column('family', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('family', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('family', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('family', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'family', 'users', ['owner_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'family', type_='foreignkey')
    op.drop_column('family', 'updated_at')
    op.drop_column('family', 'created_at')
    op.drop_column('family', 'is_active')
    op.drop_column('family', 'owner_id')
    op.drop_table('speaker_mappings')
    op.drop_table('family_members')
    # ### end Alembic commands ###
    op.drop_table('practice_session')
    op.drop_index('idx_ideal_answer_book_id', table_name='ideal_answer')
    op.drop_index('idx_ideal_answer_embedding', table_name='ideal_answer', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('ideal_answer')
    op.drop_constraint('fk_user', 'conversation', type_='foreignkey')
    op.add_column('family', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('family', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('family', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('family', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'family', 'users', ['owner_id'], ['id'])
    op.drop_column('family', 'create_date')
    op.drop_constraint('fk_userconv_conversation', 'user_conversations', type_='foreignkey')
    op.drop_constraint('user_conversations_user_id_fkey', 'user_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'user_conversations', 'conversation', ['conv_id'], ['conv_id'])
    op.create_foreign_key(None, 'user_conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_family_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_family_id_fkey', 'users', 'family', ['family_id'], ['id'])
    op.drop_constraint(None, 'user_conversations', type_='foreignkey')
    op.drop_constraint(None, 'user_conversations', type_='foreignkey')
    op.create_foreign_key('user_conversations_user_id_fkey', 'user_conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_userconv_conversation', 'user_conversations', 'conversation', ['conv_id'], ['conv_id'], ondelete='CASCADE')
    op.add_column('family', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'family', type_='foreignkey')
    op.drop_column('family', 'updated_at')
    op.drop_column('family', 'created_at')
    op.drop_column('family', 'is_active')
    op.drop_column('family', 'owner_id')
    op.create_foreign_key('fk_user', 'conversation', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.create_table('ideal_answer',
    sa.Column('snippet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('book_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l1_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l2_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l3_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canonical_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_ix', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('citation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embed_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('rag_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('snippet_id', name='ideal_answer_pkey')
    )
    op.create_index('idx_ideal_answer_embedding', 'ideal_answer', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_ideal_answer_book_id', 'ideal_answer', ['book_id'], unique=False)
    op.create_table('practice_session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('practice_session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('situation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.conv_id'], name='fk_practice_conversation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='practice_session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('analysis_result',
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False, comment='분석 결과 고유 ID'),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='대화 통계 정보 (단어 수, 문장 수 등)'),
    sa.Column('style_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='대화 스타일 분석 결과'),
    sa.Column('conversation_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='대화 턴 수'),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='대화 점수'),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True, comment='대화 요약'),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='신뢰도 점수'),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True, comment='피드백'),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='생성 시각'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='수정 시각'),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.conv_id'], name='fk_analysis_conversation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='fk_analysis_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', name='analysis_result_pkey'),
    comment='대화 분석 결과 저장 테이블'
    )
    op.create_index('idx_analysis_result_created_at', 'analysis_result', ['create_date'], unique=False)
    op.create_table('realtime_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(), server_default=sa.text("'TEXT'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['realtime_session.id'], name='realtime_message_session_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='realtime_message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='realtime_message_pkey')
    )
    op.create_table('analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practice_session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], name='analysis_practice_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analysis_pkey')
    )
    op.create_table('ideal_answer_backup',
    sa.Column('snippet_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('book_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l1_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l2_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l3_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canonical_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_ix', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('citation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embed_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('rag_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    op.create_table('realtime_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='realtime_session_family_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='realtime_session_pkey'),
    sa.UniqueConstraint('room_id', name='realtime_session_room_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('conversation_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gcs_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunked_content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('processed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('speaker_segments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speaker_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speaker_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.conv_id'], name='fk_convfile_conversation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversation_file_pkey')
    )
    op.drop_table('speaker_mappings')
    op.drop_table('family_members')
    # ### end Alembic commands ###