"""add conversation and conversation_file tables

Revision ID: be99d0c2f06d
Revises: 4cb33c98f6f4
Create Date: 2025-11-06 11:01:43.118390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be99d0c2f06d'
down_revision = '4cb33c98f6f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ref_handbook_snippet_concept_tags_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_index('ref_handbook_snippet_embedding_idx', table_name='ref_handbook_snippet', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ref_handbook_snippet_emotion_hints_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_index('ref_handbook_snippet_fts_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_index('ref_handbook_snippet_roles_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_index('ref_handbook_snippet_scenario_tags_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_index('ref_handbook_snippet_techniques_idx', table_name='ref_handbook_snippet', postgresql_using='gin')
    op.drop_table('ref_handbook_snippet')
    op.drop_table('book')
    op.drop_index('idx_ideal_answer_created_at', table_name='ideal_answer')
    op.drop_index('idx_ideal_answer_embedding', table_name='ideal_answer', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_ideal_answer_source', table_name='ideal_answer', postgresql_using='gin')
    op.drop_table('ideal_answer')
    op.drop_table('test_raw_conversation')
    op.drop_column('users', 'terms_agreed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_agreed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('test_raw_conversation',
    sa.Column('raw_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name='test_raw_conversation_pkey')
    )
    op.create_table('ideal_answer',
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('analysisid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idea_id', name='ideal_answer_pkey')
    )
    op.create_index('idx_ideal_answer_source', 'ideal_answer', [sa.text("to_tsvector('english'::regconfig, source)")], unique=False, postgresql_using='gin')
    op.create_index('idx_ideal_answer_embedding', 'ideal_answer', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_ideal_answer_created_at', 'ideal_answer', ['created_at'], unique=False)
    op.create_table('book',
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.TEXT(), server_default=sa.text("'ko'::text"), autoincrement=False, nullable=True),
    sa.Column('source_hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name='book_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ref_handbook_snippet',
    sa.Column('snippet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paragraph_ix', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('concept_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('scenario_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('techniques', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('emotion_hints', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('citation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], name='ref_handbook_snippet_book_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snippet_id', name='ref_handbook_snippet_pkey')
    )
    op.create_index('ref_handbook_snippet_techniques_idx', 'ref_handbook_snippet', ['techniques'], unique=False, postgresql_using='gin')
    op.create_index('ref_handbook_snippet_scenario_tags_idx', 'ref_handbook_snippet', ['scenario_tags'], unique=False, postgresql_using='gin')
    op.create_index('ref_handbook_snippet_roles_idx', 'ref_handbook_snippet', ['roles'], unique=False, postgresql_using='gin')
    op.create_index('ref_handbook_snippet_fts_idx', 'ref_handbook_snippet', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(summary, ''::text) || ' '::text) || COALESCE(full_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('ref_handbook_snippet_emotion_hints_idx', 'ref_handbook_snippet', ['emotion_hints'], unique=False, postgresql_using='gin')
    op.create_index('ref_handbook_snippet_embedding_idx', 'ref_handbook_snippet', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ref_handbook_snippet_concept_tags_idx', 'ref_handbook_snippet', ['concept_tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###